{% if traefik_ssl_enabled %}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.websecure.http.tls.domains[0].main={{ traefik_ssl.base_domain }}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.websecure.http.tls.domains[0].sans=*.{{ traefik_ssl.base_domain }}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.dnschallenge.provider={{ traefik_ssl.provider }}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.websecure.http.tls.certresolver={{ traefik_ssl.provider }}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.email={{ traefik_ssl.email }}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.dnschallenge.resolvers={{ traefik_ssl.resolver }}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.caServer={{ traefik_ssl.ca_server }}
{% endif %}

{% if traefik_log_level %}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --log.level={{ traefik_log_level }}
{% endif %}