kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
spec:
  template:
    spec:
      volumes:
        - name: ssl-certs
          persistentVolumeClaim:
            claimName: traefik-ssl-certs
          env:
          - name: CLOUDFLARE_EMAIL
            valueFrom:
              secretKeyRef:
                key: email
                name: cloudflare-api-credentials
          - name: CLOUDFLARE_DNS_API_TOKEN
            valueFrom:
              secretKeyRef:
                key: apiKey
                name: cloudflare-api-credentials
      containers:
        - name: traefik
          volumeMounts:
          - name: ssl-certs
            mountPath: /certs
      initContainers:
        - name: volume-permissions 
          image: busybox:1.31.1 
          command: ["sh", "-c", "chmod -Rv 600 /certs/*"] 
          volumeMounts: 
            - name: ssl-certs 
              mountPath: /certs