{% if traefik_ssl_enabled %}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.websecure.Address=:443
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.dnschallenge=true
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.email={{ traefik_ssl.cloudflare_email }}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.storage=/certs/acme.json
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.web.http.redirections.entrypoint.to=websecure
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.web.http.redirections.entrypoint.scheme=https
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.websecure.http.tls=true
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.websecure.http.tls.certResolver=cloudflare
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.websecure.http.tls.domains[0].main={{ traefik_ssl.base_domain }}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --entrypoints.websecure.http.tls.domains[0].sans=*.{{ traefik_ssl.base_domain }}
{% endif %}

{% if traefik_ssl_stage_enabled %}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --certificatesresolvers.cloudflare.acme.caServer={{ traefik_ssl_stage }}
{% endif %}

{% if auto_dns_enabled %}
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --providers.file.filename=/config/external-traefik-services.yaml
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: --providers.file.watch=true
{% endif %}