kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
spec:
  template:
    spec:
      containers:
        - name: traefik
          args:
            - --log.level={{ traefik_log_level }}