kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
spec:
  template:
    spec:
      volumes:
        - name: file-provider
          configMap:
            name: external-traefik-services-config
      containers:
        - name: traefik
          volumeMounts:
            - name: file-provider
              mountPath: /config