http:
  services:
{% for service in external_services.services %}
    {{service.cname}}:
      loadBalancer:
        servers:
          - url: {{service.service_address}}
{% endfor %}
  routers:
{% for service in external_services.services %}
    {{service.cname}}:
      entryPoints:
        - websecure
      service: {{service.cname}}
      rule: Host(`{{service.cname}}.{{env_base_domain}}`) && PathPrefix(`/`)
{% endfor %}
