http:
  services:
    vault:
      loadBalancer:
        servers:
          - url: http://10.0.0.50
  routers:
    vault:
      entryPoints:
        - websecure
      service: vault
      rule: Host(`vault.graytonward.com`) && PathPrefix(`/`)