apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- ../../base
{% if traefik_ssl_enabled %}
- dashboard-ingress.yaml
- ssl-cert-pvc.yaml
- sealed-cloudflare-credentials.yaml
{% endif %}
patches:
- path: deployment-args-patch.yaml
  target:
    kind: Deployment
    name: traefik-deployment
{% if traefik_ssl_enabled %}
- path: deployment-ssl-patch.yaml
  target:
    kind: Deployment
    name: traefik-deployment
{% endif %}
{% if auto_dns_enabled %}
- path: deployment-file-provider-patch.yaml
  target: 
    kind: Deployment
    name: traefik-deployment
{% endif %}

{% if auto_dns_enabled %}
configMapGenerator:
  - name: external-traefik-services-config
    namespace: kube-system
    options:
      disableNameSuffixHash: true
    files:
      - external-traefik-services.yaml
{% endif %}