apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik
resources:
- ../../base
{% if traefil_ssl_enabled %}
- dashboard-ingress.yaml
{% endif %}
patches:
{% if traefik_ssl_enabled %}
- path: deployment-patch.yaml
  target:
    kind: Deployment
    name: traefik-deployment
{% endif %}
