apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: traefik
spec:
  encryptedData:
    apiKey: {{ traefik_ssl.cloudflare_api_key }}
    email: {{ traefik_ssl.cloudflare_email }}
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: traefik