apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-credentials
  namespace: traefik
  annotations:
    sealedsecrets.bitnami.com/patch: "true"
spec:
  encryptedData:
    apiKey: {{ traefik_ssl.cloudflare_api_key }}
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-credentials
      namespace: traefik
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: traefik
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
stringData:
  email: {{ traefik_ssl.cloudflare_email }}
