{% for service in external_services.services %}
---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: {{service.cname}}-dns
spec:
  endpoints:
  - dnsName: {{service.cname}}.{{env_base_domain}}
    recordTTL: 180
    recordType: A
    targets:
    - 10.0.0.91
{% endfor %}