apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: vault-dns
  namespace: dns
spec:
  endpoints:
  - dnsName: vault.graytonward.com
    recordTTL: 180
    recordType: A
    targets:
    - 10.0.0.90