apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-web-password
  namespace: pihole
spec:
  encryptedData:
    password: {{ pihole_web_password }}
  template:
    metadata:
      creationTimestamp: null
      name: pihole-web-password
      namespace: pihole