routedNamespaces:
- pirate-ship
addons:
  vpn:
    enabled: true
    type: openvpn
    openvpn:
      authSecret: openvpn-credentials
    configFileSecret: openvpn-credentials
    livenessProbe:
      exec:
        command:
          - sh
          - -c
          - if [ $(wget -q -O- https://ipinfo.io/country) == 'US' ]; then exit 0; else exit $?; fi
      initialDelaySeconds: 30
      periodSeconds: 60
      failureThreshold: 1
    networkPolicy:
      enabled: ture
      egress:
        - to:
          - ipBlock:
              cidr: 0.0.0.0/0
          ports:
          - port: 443
            protocol: UDP
        - to:
          - ipBlock:
              cidr: 10.0.0.0/8
settings:
  VPN_INTERFACE: tun0
  VPN_BLOCK_OTHER_TRAFFIC: true
  VPN_TRAFFIC_PORT: 443
  VPN_LOCAL_CIDRS: "10.0.0.0/8"
