apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
helmCharts:
- name: podinfo
  includeCRDs: true
  releaseName: podinfo
  version: 6.3.6
  repo: https://stefanprodan.github.io/podinfo