apiVersion: apps/v1
kind: Deployment
metadata:
  name: palworld
  labels:
    app.kubernetes.io/name: palworld
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: palworld
  template:
    metadata:
      labels:
        app.kubernetes.io/name: palworld
    spec:
      containers:
      - name: palworld
        image: ghcr.io/graytonio/palworld-server:473987551a03111f6189f77ea5bd7970f110efe0
        args: [
          "./PalServer.sh",
          "--useperfthreads", 
          "-NoAsyncLoadingThread -UseMultithreadForDS"
        ]
        ports:
          - containerPort: 8221
            protocol: TCP
        resources:
          limits:
            memory: "8Gi"
            cpu: "4"
---
apiVersion: v1
kind: Service
metadata:
  name: palworld
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.95
  selector:
    app.kubernetes.io/name: palworld
  ports:
  - name: server
    port: 8221
    targetPort: 8221

