radarr:
  enabled: true
  controller:
    strategy: Recreate
  image:
    tag: 4.5.2
  podLabels:
    app.kubernetes.io/name: pirate-ship-radarr
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: radarr.png                                                                                                         
        gethomepage.dev/name: Radarr
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany

sonarr:
  enabled: true
  controller:
    strategy: Recreate
  image:
    tag: 3.0.10
  podLabels:
    app.kubernetes.io/name: pirate-ship-sonarr
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: sonarr.png                                                                                                         
        gethomepage.dev/name: Sonarr
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany

prowlarr:
  enabled: true
  image:
    tag: 1.5.2
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: prowlarr.png                                                                                                         
        gethomepage.dev/name: Prowlarr
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image: 
          repository: qmcgaw/gluetun
          tag: v3.35
      networkPolicy:
        enabled: ture
        egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: 443
              protocol: UDP
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8

transmission:
  enabled: true
  image:
    tag: 4.0.3
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: transmission.png                                                                                                         
        gethomepage.dev/name: Transmission
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image: 
          repository: qmcgaw/gluetun
          tag: v3.35
      networkPolicy:
        enabled: ture
        egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: 443
              protocol: UDP
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8

nzbget:
  enabled: true
  image:
    tag: 21.1.20230119
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: nzbget.png                                                                                                         
        gethomepage.dev/name: NZBget
  env:
    NZBGET_USER: "nzbget"
    NZBGET_PASS: "tegbzn6789"
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image: 
          repository: qmcgaw/gluetun
          tag: v3.35
      networkPolicy:
        enabled: ture
        egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: 443
              protocol: UDP
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8

overseerr:
  enabled: true
  image:
    tag: 1.33.0
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: overseerr.png                                                                                                         
        gethomepage.dev/name: Overseerr