radarr:
  enabled: true
  controller:
    strategy: Recreate
  image:
    tag: 4.5.2
  podLabels:
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: radarr.png                                                                                                         
        gethomepage.dev/name: Radarr
        gethomepage.dev/pod-selector: app.kubernetes.io/name=radarr
        gethomepage.dev/widget.type: radarr
        gethomepage.dev/widget.url: http://pirate-ship-radarr.pirate-ship.svc:7878
        gethomepage.dev/widget.key: ba41a262d1f448f58627ec6d8de4ad9c
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany

sonarr:
  enabled: true
  controller:
    strategy: Recreate
  image:
    tag: 3.0.10
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: sonarr.png                                                                                                         
        gethomepage.dev/name: Sonarr
        gethomepage.dev/pod-selector: app.kubernetes.io/name=sonarr
        gethomepage.dev/widget.type: radarr
        gethomepage.dev/widget.url: http://pirate-ship-sonarr.pirate-ship.svc:8989
        gethomepage.dev/widget.key: 1333b9a2e3044e898c5d3654c2c60ccc
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany

prowlarr:
  enabled: true
  image:
    tag: 1.5.2
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: prowlarr.png                                                                                                         
        gethomepage.dev/name: Prowlarr
        gethomepage.dev/pod-selector: app.kubernetes.io/name=prowlarr
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image: 
          repository: qmcgaw/gluetun
          tag: v3.35
      networkPolicy:
        enabled: ture
        egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: 443
              protocol: UDP
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8

transmission:
  enabled: true
  image:
    tag: 4.0.3
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: transmission.png                                                                                                         
        gethomepage.dev/name: Transmission
        gethomepage.dev/pod-selector: app.kubernetes.io/name=transmission
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image: 
          repository: qmcgaw/gluetun
          tag: v3.35
      networkPolicy:
        enabled: ture
        egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: 443
              protocol: UDP
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8

nzbget:
  enabled: true
  image:
    tag: 21.1.20230119
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: nzbget.png                                                                                                         
        gethomepage.dev/name: NZBget
        gethomepage.dev/pod-selector: app.kubernetes.io/name=nzbget
  env:
    NZBGET_USER: "nzbget"
    NZBGET_PASS: "tegbzn6789"
  addons:
    vpn:
      enabled: true
      type: gluetun
      gluetun:
        image: 
          repository: qmcgaw/gluetun
          tag: v3.35
      networkPolicy:
        enabled: ture
        egress:
          - to:
            - ipBlock:
                cidr: 0.0.0.0/0
            ports:
            - port: 443
              protocol: UDP
          - to:
            - ipBlock:
                cidr: 10.0.0.0/8

overseerr:
  enabled: true
  image:
    tag: 1.33.0
  persistence:
    config:
      enabled: true
      size: 10Gi
      accessMode: ReadWriteMany
  ingress:
    main:
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Media
        gethomepage.dev/icon: overseerr.png                                                                                                         
        gethomepage.dev/name: Overseerr
        gethomepage.dev/pod-selector: app.kubernetes.io/name=overseerr