ingress:
  main:
    enabled: true
    hosts:
      - host: portal.{{ env_base_domain }}
        paths:
          - path: /
            pathType: ImplementationSpecific
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: "{% if traefik_ssl_enabled %}websecure{% else %}web{% endif %}"