{% if traefik_ssl_enabled %}
ingress:
  main:
    enabled: true
    hosts:
      - host: portal.{{ traefik_ssl.base_domain }}
        paths:
          - path: /
            pathType: ImplementationSpecific
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
{% endif %}