apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openvpn-credentials
  namespace: pirate-ship
spec:
  encryptedData:
    openvpn-password: {{ pirate_ship_vpn.openVPNPassword }}
    openvpn-user: {{ pirate_ship_vpn.openVPNUser }}
  template:
    metadata:
      creationTimestamp: null
      name: openvpn-credentials
      namespace: pirate-ship

