prowlarr:
  addons:
    vpn:
      env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-user
        - name: OPENVPN_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-password
        - name: VPN_INTERFACE
          value: tun0
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        - name: DOT
          value: "off"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.0.0.0/8"
        - name: SERVER_REGIONS
          value: {{ pirate_ship_vpn.region }}

transmission:
  addons:
    vpn:
      env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-user
        - name: OPENVPN_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-password
        - name: VPN_INTERFACE
          value: tun0
        - name: SERVER_REGIONS
          value: {{ pirate_ship_vpn.region }}

nzbget:
  addons:
    vpn:
      env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-user
        - name: OPENVPN_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-password
        - name: VPN_INTERFACE
          value: tun0
        - name: SERVER_REGIONS
          value: {{ pirate_ship_vpn.region }}