radarr:
  ingress:
    main:
      enabled: {{ traefik_ssl_enabled }}
      hosts:
        - host: radarr.{{ traefik_ssl.base_domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific

sonarr:
  ingress:
    main:
      enabled: {{ traefik_ssl_enabled }}
      hosts:
        - host: sonarr.{{ traefik_ssl.base_domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific

prowlarr:
  ingress:
    main:
      enabled: {{ traefik_ssl_enabled }}
      hosts:
        - host: prowlarr.{{ traefik_ssl.base_domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
  addons:
    vpn:
      env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-user
        - name: OPENVPN_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-password
        - name: VPN_INTERFACE
          value: tun0
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        - name: DOT
          value: "off"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.0.0.0/8"
        - name: SERVER_REGIONS
          value: {{ pirate_ship_vpn.region }}

transmission:
  ingress:
    main:
      enabled: {{ traefik_ssl_enabled }}
      hosts:
        - host: transmission.{{ traefik_ssl.base_domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
  addons:
    vpn:
      env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-user
        - name: OPENVPN_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-password
        - name: VPN_INTERFACE
          value: tun0
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        - name: DOT
          value: "off"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.0.0.0/8"
        - name: SERVER_REGIONS
          value: {{ pirate_ship_vpn.region }}

nzbget:
  ingress:
    main:
      enabled: {{ traefik_ssl_enabled }}
      hosts:
        - host: nzbget.{{ traefik_ssl.base_domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific
  addons:
    vpn:
      env:
        - name: VPN_SERVICE_PROVIDER
          value: private internet access
        - name: OPENVPN_USER
          valueFrom:
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-user
        - name: OPENVPN_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: openvpn-credentials
              key: openvpn-password
        - name: VPN_INTERFACE
          value: tun0
        - name: DNS_KEEP_NAMESERVER
          value: "on"
        - name: DOT
          value: "off"
        - name: FIREWALL_OUTBOUND_SUBNETS
          value: "10.0.0.0/8"
        - name: SERVER_REGIONS
          value: {{ pirate_ship_vpn.region }}

overseerr:
  ingress:
    main:
      enabled: {{ traefik_ssl_enabled }}
      hosts:
        - host: netflix.{{ traefik_ssl.base_domain }}
          paths:
            - path: /
              pathType: ImplementationSpecific