apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
  - name: longhorn
    releaseName: longhorn
    version: 1.5.0
    repo: https://charts.longhorn.io
    valuesInline:
      ingress:
        enabled: true
      persistence:
        defaultClass: true
{% if longhorn_backups_enabled %}
      defaultSettings: 
        backupTarget: {{ longhorn_backups }}
        backupTargetCredentialSecret: b2-credentials
{% endif %}