apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn-system
resources:
- dashboard-ingress.yaml
{% if longhorn_backups_enabled %}
- sealed-b2-credentials.yaml
{% endif %}