apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: b2-credentials
  namespace: longhorn-system
spec:
  encryptedData:
    AWS_ACCESS_KEY_ID: {{ longhorn_backups.access_id }}
    AWS_ENDPOINTS: {{ longhorn_backups.endpoints }}
    AWS_SECRET_ACCESS_KEY: {{ longhorn_backups.access_key }}
  template:
    metadata:
      creationTimestamp: null
      name: b2-credentials
      namespace: longhorn-system

