ingress:
  host: longhorn.{{ env_base_domain }}
{% if longhorn_backups_enabled %}
defaultSettings: 
  backupTarget: {{ longhorn_backups.target }}
  backupTargetCredentialSecret: b2-credentials
{% endif %}