kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --api.insecure
            - --entrypoints.web.Address=:80
            - --providers.kubernetesingress
            - --providers.kubernetesIngress.publishedService.enabled=true
            - --providers.kubernetesingress.ingressEndpoint.publishedService=traefik/traefik-service
            - --providers.kubernetescrd
          ports:
            - name: web
              containerPort: 80
            - name: websecure
              containerPort: 443
            - name: dashboard
              containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "4Gi"
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.91
  ports:
    - name: web
      targetPort: 80
      port: 80
    - name: websecure
      targetPort: 443
      port: 443
    - name: dashboard
      targetPort: dashboard
      port: 8080
  selector:
    app: traefik