name: Build K8S Manifests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  repository_dispatch:
    types:
      - FLAG_UPDATED
permissions:
  contents: write
jobs:
    build-infra:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                go-version: '1.20'
            - run: go install github.com/graytonio/flagops@latest
            - run: make prod # TODO staging -> production
            - uses: EndBug/add-and-commit@v9
              with:
                message: Rebuild Deployed Infrastructure
                committer_name: FlagOps
                committer_email: actions@github.com