name: Build K8S Manifests
on: push
jobs:
    build-infra:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                go-version: '1.20'
            - run: go install github.com/graytonio/flagops@latest
            - uses: EndBug/add-and-commit@v9
              with:
                committer_name: FlagOps
                committer_email: actions@github.com